server:
  port: 7777
spring:
  application:
    name: Traccer2
  datasource:
    username: postgres
    password: pro100shoh
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/traccer
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

